import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import Footer from '../components/footer'
import { ToastProvider } from '@/components/providers/toaster-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en' >
        <body className={`flex min-h-screen flex-col ${inter.className}`}>

            {/* <Header /> */}
            <main className='grow'>
              <ToastProvider />
              {children}
              </main>
            <Footer />
          
        </body>
      </html>
    </ClerkProvider>
  )
}
